name: Angular Build
on:
  push:
    branches: main
    paths: 
    - 'frontend/**'

jobs:
  main:
    runs-on: Ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: asmahadoop
          password: dckr_pat_3i6rPUFP5Ud5Fc8MxXn8fZ9hWIU
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: frontend/.
          file: frontend/Dockerfile
          push: true
          tags: asmahadoop/mean-angular:latest
          secrets: |
            GIT_AUTH_TOKEN=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
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
